[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
atomic_exchange = "EimKomGHHSt21ie5F5DRQdgKmU9NwCfBgQtGKvmPGMfb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[hooks]
